### ISSUE TITLE
Our Goals - copy outside of accordions.

### ISSUE THREAD

**Issue by danhon** [CA-CODE-Works/Vision-2023#10]
I think we'll need some introduction text ahead of the goal accordions. 

FYI draft text is here, will need to edit down:

We have set five broad goals to achieve Vision 2023. In the next three years and beyond, we must: 

- Deliver easy-to-use, fast, dependable and secure public services.
- Ensure public services are equitable and inclusive.
- Make common technology easy to access, use, and reuse across government.
- Build digital government more quickly and more effectively. 
- Build confident, empowered multi-disciplinary teams.

To achieve these goals, we must also understand what challenges stand in our way. 

To inspire leaders and teams who would like to engage in this transformation and to work together across government, we have highlighted key challenges we’ll need to face to achieve each goal. We have chosen these challenges based on our interviews and research to help us to set specific objectives and results for us to achieve each year. 

We have deliberately chosen to concentrate on these goals and challenges to build momentum, alignment and trust. Making progress here is key to using technology proactively instead of reactively as we emerge from 2020. 

We hope to inspire leaders and teams to help us set specific objectives and key results. We can achieve Vision 2023 by charting the path forward together, and holding ourselves accountable to doing the hard work over the next few years.

**Comment by kkoryaka** [comment]
Thanks. Added intro text to the goals page
