### ISSUE TITLE
References / "Vision 2023 benefits from the work of"

### ISSUE THREAD

**Issue by danhon** [CA-CODE-Works/Vision-2023#16]
* Make sure it reflects final copy, indented layout and includes links
* retitle and update url to /references/ or references.html

**Comment by timothyshambra** [comment]
- [x] Retitled
- [ ] update list

**Comment by timothyshambra** [comment]
@danhon  - Does not look like any of the hyperlinks transferred over from the word document, nor pdf or google docs that I can find. I manually searched/added them. Can you run through them when you get a chance, and ping me of any changes needed? Thank you!

**Comment by danhon** [comment]
Yep, checking now.

**Comment by danhon** [comment]
@timothyshambra Have checked and submitted a PR of changes.
