### ISSUE TITLE
Vision/story page at /vision/ needs linking in homepage intro copy

### ISSUE THREAD

**Issue by danhon** [CA-CODE-Works/Vision-2023#25]
The vision/story page at /vision/ is unlinked.

Potential places for it to be linked:

* top nav
* footer 

Gut feeling is that it need to be linked from the top copy block on the homepage, above the "provide input" and "explore challenges".

**Comment by danhon** [comment]
Sorry, going too fast. I see it's linked in the footer. 

It needs to be linked higher up as it's intended to be the human, relatable pitch for Vision 2023.

**Comment by timothyshambra** [comment]
The main nav is getting crowded. What if we rename some of the menu links...

1. Home
2. Our Vision
2. Principles
3. Goals
4. Challenges
5. What's Next

![Screen Shot 2021-01-15 at 10 26 39 AM](https://user-images.githubusercontent.com/20093966/104764390-31bb6e80-571c-11eb-95ab-c2ac846cc13f.png)
![Screen Shot 2021-01-15 at 10 23 55 AM](https://user-images.githubusercontent.com/20093966/104764395-341dc880-571c-11eb-8c00-0a0ff62dbe58.png)

**Comment by danhon** [comment]
Yeah, it's definitely getting crowded. 

Agree on removing "Our".
