### ISSUE TITLE
URL structure for goals

### ISSUE THREAD

**Issue by danhon** [CA-CODE-Works/Vision-2023#5]
I'd like to suggest slugs/URLs for the challenges like

/goals/deliver-clear-fast-secure-dependable-public-services/index.md
/goals/equity-and-inclusion/index.md
/goals/share-and-reuse-technology/index.md
/goals/transform-government/index.md
/goals/multi-disciplinary-teams/index.md

**Comment by timothyshambra** [comment]
Thank you @danhon  - I'll bring this up in the next review.

**Comment by danhon** [comment]
Great! also I see that /challenges/[goal-description]/ might make more sense.

**Comment by kkoryaka** [comment]
Is this suggestion for static website goals page or githup goals page?
