### ISSUE TITLE
Update navigation bar in header

### ISSUE THREAD

**Issue by danhon** [CA-CODE-Works/Vision-2023#6]
Navigation bar header should be reordered semantic order of homepage (currently goals->what's next->guiding principles)

1. Guiding principles
2. Our goals
3. What's next

![Screen Shot 2021-01-14 at 1 29 49 PM](https://user-images.githubusercontent.com/518444/104651490-94edc800-566c-11eb-978d-50f30f9a8a22.png)

**Comment by kkoryaka** [comment]
You got it. Art also suggested to add explore challenges since it's our main call to action so far. So, I have added it too

**Comment by danhon** [comment]
Thanks!

Let's put Explore Challenges between Our Goals and What's Next, so:

1. Guiding Principles
2. Our Goals
3. Explore Challenges
4. What's Next

**Comment by kkoryaka** [comment]
You got it. Kimberly also suggested to change Guiding Principle to Our Principles. So it will be:
1. Our Principles
2. Our Goals
3. Explore Challenges
4. What's Next

**Comment by timothyshambra** [comment]
We also added a link to the homepage for easier navigation.

1. Home
2. Our Principles
3. Our Goals
4. Explore Challenges
5. What's Next
