### ISSUE TITLE
Letter from the State CIO needs to be its own page, not a modal

### ISSUE THREAD

**Issue by danhon** [CA-CODE-Works/Vision-2023#7]
See: https://staging.vision2023.cdt.ca.gov

Letter doesn't work for mobile/responsive design when it's a modal.

![Screen Shot 2021-01-14 at 1 17 32 PM](https://user-images.githubusercontent.com/518444/104650328-e006db80-566a-11eb-898c-e3e1fff3d98d.png)

**Comment by kkoryaka** [comment]
That was suggested by our UX expert Byron. Please contact him.

**Comment by timothyshambra** [comment]
After review, we will be creating a new page with the letter contents.

**Comment by timothyshambra** [comment]
This page has been created https://vision2023.cdt.ca.gov/letter/
