### ISSUE TITLE
Implement Vision 2023 "story"?

### ISSUE THREAD

**Issue by danhon** [CA-CODE-Works/Vision-2023#9]
VERY late feedback on this, but hopefully not too difficult to implement. 

Was there a decision to not implement the story involving MW (formerly Mateo) and Kimberly?

**Comment by kkoryaka** [comment]
@danhon Could you please point to the specific page and suggest changes?

**Comment by danhon** [comment]
There's no page with the copy. Pasted version of copy without formatting is here, Kimberly can supply Word/Google Docs version.

Our vision
A trip to 2023 and beyond
Imagine if government worked like this: 

When MW loses their job, whether during an emergency like COVID-19 or a recession, they can apply for unemployment insurance with their baby on their hip in one hand, and their phone in the other. In minutes, the unemployment insurance money MW needs is in their bank account, ready to use. 

MW gets the help they need quickly. It means they can put food on the table, supporting a local store. Supporting MW and everyone like them makes our neighborhoods and communities stronger. 

We can make this happen. We keep the promise of public service by ensuring every Californian has the information and help they need when they need it with compassion, ease and urgency. 

*

Meanwhile, Kimberly, a state staffer, has an idea for a faster, simpler way for her program to help Mateo. It takes just seconds for her to find the right colleague in another department to work with. They work together in real-time instantly, from home, in their offices, or in the field. 

With standard, readily available tools, using secure data held by the state, and building on the successes and failures of teams before her, Kimberly and her colleagues build a simple mobile website to test their idea with real people. After a few tweaks based on what they’ve learned, Kimberly’s idea works. Sharing the team’s solution and results, their idea is put in place. 

Two weeks after Kimberly had her idea, all of California’s 40 million residents can benefit from her focus on making people’s lives better. 

Kimberly and her team’s names go up on her department’s wall celebrating all the small, quick changes improving lives. What Kimberly and her team learned — what didn’t work, what did, and what they changed — goes straight into improving the systems, tools, guides and advice for putting the next idea for improvement into place, wherever it appears. 

*
We can make this vision real 

Our vision of the future is inspired by thousands of passionate, dedicated public servants across all of government, our legislature, local governments, and the technology community who all provided input to this strategic plan. 

The people we talked to shared their passions, dreams, and what’s getting in our way. We heard their ideas about what needs to change, and how we might make that change together. 

We can make this vision real by bringing every part and discipline of government to work together, using technology as a lever to listen to people, help people, and improve at what we do, every single day.

**Comment by danhon** [comment]
Actual copy is in the Word doc in Teams, see Kimberly's message here:

https://teams.microsoft.com/l/message/19:a205c6402d344e4b9a7215c645d42f04@thread.skype/1610671838155?tenantId=52b26be4-7f5d-4e1c-baed-8cf75b7570d5&groupId=cf58a66a-3a2a-4510-a2be-029e24b05255&parentMessageId=1610665345715&teamName=Vision%202023%20Collaboration%20Space&channelName=Web%20and%20Branding&createdTime=1610671838155
